data_params:
  data_path: ./dataset/
  num_workers: 4
  patch_size: 256
  train_batch_size: 128
  val_batch_size: 128
exp_params:
  LR: 0.001
  kld_weight: 1
  manual_seed: 1265
  scheduler_gamma: 0.97
  weight_decay: 0.5
logging_params:
  manual_seed: 1265
  name: DIPVAE
  save_dir: logs/
model_params:
  in_channels: 3
  lambda_diag: 0.05
  lambda_offdiag: 0.1
  latent_dim: 64
  name: DIPVAE
trainer_params:
  gpus:
  - 3
  max_epochs: 25
