name: kitchen-multiview-all-v0
args: []
kwargs: {}
obs_dim: 512
action_dim: 9
action_min: null
action_max: null

# load_dir: "/home/chenyu/Desktop/DDRL_project/bet/exp_local/2024.04.02/113841_kitchen_train" # original
load_dir: "/home/chenyu/Desktop/DDRL_project/bet/exp_local/2024.04.11/133911_kitchen_train" #resnet 512

workspace:
  _target_: workspaces.adept_kitchen.AdeptKitchenWorkspace

dataset_fn:
  _target_: dataloaders.trajectory_loader.get_relay_kitchen_multiview_train_val
  data_directory: ${env_vars.datasets.relay_kitchen}
  window_size: ${window_size}
  encoder:
    _target_: models.resnet.resnet18
    output_dim: 512
    pretrained: True
    freeze_pretrained: True
